steps:
  # Step 1: Build the Java project using Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install']

  # Step 2: Build the Docker image using the Dockerfile in the root of the repository
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-image-name', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-image-name']

  # Step 4: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'your-service-name'
      - '--image'
      - 'gcr.io/$PROJECT_ID/your-image-name'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

# Substitutions (Optional)
substitutions:
  _IMAGE_NAME: 'your-image-name'
  _SERVICE_NAME: 'your-service-name'
  _REGION: 'us-central1'
